package com.projeto.sistema.modelos;

public enum Permissao {
    USUARIO_VISUALIZAR, USUARIO_CRIAR, USUARIO_EDITAR, USUARIO_EXCLUIR,
    CONTATO_VISUALIZAR, CONTATO_CRIAR, CONTATO_EDITAR, CONTATO_EXCLUIR,
    GRUPO_VISUALIZAR, GRUPO_CRIAR, GRUPO_EDITAR, GRUPO_EXCLUIR,
    
    MENSAGEM_ENVIAR,
    RELATORIO_GERAR,
    CONFIGURACOES_SISTEMA, // <-- Faltava a vírgula bem aqui!
    
    AGENDA_VISUALIZAR,
    AGENDA_CRIAR,
    AGENDA_EDITAR,
    AGENDA_EXCLUIR,

    MENSAGEM_VISUALIZAR,
    MENSAGEM_CRIAR,
    MENSAGEM_EXCLUIR,
    
    RELATORIO_VISUALIZAR; // <-- Ponto e vírgula no final (boa prática)
}