package com.projeto.sistema.modelos;

public enum Permissao {
    USUARIO_VISUALIZAR, USUARIO_CRIAR, USUARIO_EDITAR, USUARIO_EXCLUIR,
    CONTATO_VISUALIZAR, CONTATO_CRIAR, CONTATO_EDITAR, CONTATO_EXCLUIR,
    GRUPO_VISUALIZAR, GRUPO_CRIAR, GRUPO_EDITAR, GRUPO_EXCLUIR,
    MENSAGEM_ENVIAR,
    RELATORIO_GERAR,
    CONFIGURACOES_SISTEMA
}